name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.9
  - pyaudio
  - speechrecognition
  - transformers
  - pip
  - pip:
      - torch
      - opencv-python
      - deepl